### ISSUE TITLE
If you have a problem running a start.sh script 

### ISSUE THREAD

**Issue by jovan99djokic** [maciejpuzianowski/ecommerce-platform#1]
I notice that i cannot run start.sh file and then i do a little research. Finally i found that the problem was - (dash) inside start.sh script because there is a difference between docker compose and docker-compose.

So if anyone have a problem with running the start.sh script just remove dash at 43. line docker compose up --build -d || { echo "Failed to start services with Docker Compose"; exit 1; }

**Comment by maciejpuzianowski** [comment]
Hi, thanks for noticing. It is due to docker compose version. Have a look: https://stackoverflow.com/a/66516826
